import LocalizedStrings from 'react-native-localization';

export default new LocalizedStrings({
  ar: {
    NewMessage: 'لديك رسالة جديدة',
    OpenMessage: 'هل تريد فتح الرسائل',
    close: 'إغلاق',
    ShareApp: 'شارك التطبيق',
    DownloadSouqHaretna: ':حمل تطبيق صوغة',
    AppPolicy: 'سياسة التطبيق',
    StoreroomsAdded: ' المذاخر المضافه للسله',
    AvailableLanguages: 'اللغات المتوفرة',
    resendOtp: 'اعاده ارسال الرمز',
    Messages: 'الرسائل',
    Enterotp: 'ادخل رمز التحقق ',
    Minimumpoints: 'الحد الأدنى لأستبدال النقاط',
    applicationCanOnly:
      'لا يمكنك استخدام التطبيق الا اذا تم تسجيل صيدليه خاصه بك',
    WhichCategory: 'في أي قسم ترغب نشر إعلانك ؟',
    IsUserName: 'هذا الاسم موجود ',
    IsPhone: 'هذا الرقم موجود  ',
    totalpoint: 'رصيد النقاط غير كافية للأستبدال ',
    facebook: 'تواصل على الفيس بوك ',
    whatsappContact: 'تواصل على الواتس اب',
    instagram: 'تواصل على الأنستقرام ',
    LoginFirst: 'يجب عليك تسجيل الدخول لرؤية الرسائل',
    Report: 'إبلاغ',
    OrderNum: 'رقم الطلب :',
    OrderOmnerName: 'أسم المشتري :',
    IncorrectNumber: 'رقم المستخدم غير صحيح',
    ShareMsg: 'شاهد هذا الإعلان على تطبيق صوغه',
    searchProduct: 'بحث عن المنتجات',
    SouqHaretnaDesc:
      'صوغه: الموقع الأحدث في العراق للبيع و البحث عن العقارات, السيارات',
    EducationLevel: 'درجة التعليم',
    EditAdv: 'تعديل اعلان',
    Location: 'الموقع',
    SelectLocation: 'اختيار الموقع',
    Automatic: 'اوتوماتيك',
    Manual: 'يدوي',
    GearType: 'ناقل الحركة',
    SelectPrice: 'قم بتحديد السعر',
    Model: 'الموديل',
    whatsapp: 'أرجو تنزيل تطبيق الواتس أب',
    SelectColor: 'قم بتحديد اللون',
    Price: 'السعر',
    SelectKind: 'اختر الفئة',
    Kind: 'الفئة',
    SubCategory: 'القسم الفرعي',
    ChooseSubCat: 'اختر القسم الفرعي',
    SelectType: 'اختر النوع',
    ChooseMainCat: 'الرجاء اختيار القسم الرئيسي',
    Type: 'النوع',
    AllCats: 'جميع الأقسام',
    IraqDinar: 'دع',
    Dollar: 'دولار',
    NoItems: 'لا يوجد عناصر',
    SaveChanges: 'حفظ التغيرات',
    PostGeneralInformation: 'معلومات الإعلان الرئيسية',
    Name: 'الإسم',
    MyFavourites: 'الاعلانات المفضلة',
    MyAds: 'اعلاناتي',
    WhichSubCategory: 'الرجاء اختيار التصنيف الفرعي لإعلانك',
    AddAdvertisment: 'نشر إعلاني مجانا على صوغه',
    AddAdvertismentHeader: 'نشر إعلان',
    EnterWordToSearch: 'الرجاء ادخال كلمة  للبحث',
    ChooseCat: 'اختيار الفئة',
    CategoriesSearch: 'قسم البحث',
    AddAdvs: 'اضف اعلان مجانا',
    ShowMore: '  عرض المزيد',
    SeeCatgs: 'تصفح الأقسام',
    LatestAds: 'احدث الاعلانات',
    LoginNow: 'سجَل دخولك الان',
    HaveAccount: 'تمتلك حساب؟',
    FillCorrect: 'يرجى تعبئة البيانات بشكل سليم',
    TryAgain: 'يرجى المحاولة بعد قليل',
    EmailUsed: 'البريد الالكتروني مستخدم',
    AndPrivacy: 'وخصوصية الموقع',
    Terms: 'شروط الإستخدام',
    ByContinuing: ' بإستمرارك انت توافق على',
    LoginOperation: 'عملية التسجيل',
    Skip: 'تخطي',
    YouCan: 'يمكنك',
    RegisterNow: 'سجَل الان',
    NoAccount: 'لا تمتلك حساب؟',
    EmailOrPassIncorrect: 'خطا في كلمة المرور او بالبريد الالكتروني',
    ProductRelated: 'اعلانات ذات صلة',
    savedChanges: 'تم حفظ التغيرات بنجاح',
    owner: 'صاحب الصيدليه',
    search: 'البحث',
    Share: 'مشاركة ',
    Town: 'المحافظة',
    EditUser: 'تعديل المعلومات',
    SelectTown: 'اختر المحافظة',
    Home: 'الرئيسية',
    MustLogin: 'يجب عليك تسجيل الدخول اولاً',
    EditProfile: 'تعديل الحساب',
    WrongCode: 'الرمز خاطىء',
    BackToLogin: 'العودة الى تسجيل الدخول',
    Back: 'العودة',
    SomethingWentWrong: 'حصل خطأ ما',
    PasswordChanged: 'تم تغيير كلمة السر بنجاح',
    PasswordDoesntMatch: 'كلمة السر لم تتطابق',
    PasswordIsShort: 'كلمة السر قصيرة',
    NewPassword: 'كلمة السر الجديدة',
    ConfirmPassword: 'تأكيد كلمة السر',

    VerifyText: 'بإرسال رمز التحقق.. أرجو الأنتظار ',
    YourCode: 'رقم التأكيد', //otp code placeholder
    Verify: 'تحقق',
    Resend: 'إعادة إرسال',
    send: 'إرسال',
    ForgotPassword: 'نسيت كلمة السر؟',
    Submit: 'أرسل',
    EnterEmail: 'أدخل بريدك الأكتروني و سوف نرسل لك رقم التأكيد',
    InvalidEmail: 'عنوان البريد الإلكتروني غير صالح',

    PrivacyAndPolicy: 'بإستمرارك انت توافق على شروط الإستخدام وخصوصية الموقع.',
    Title: 'عنوان المنتج',
    SelectTitle: 'مثال منازل للبيع بسعر مغري',
    Description: 'وصف',
    SelectDescription: 'ادخل الوصف',
    Photos: 'اضافه صور للمنتج',
    NoTitle: 'الرجاء تعبئة اسم أو موضوع المنتج',
    ChooseKind: 'الرجاء اختيار  الفئة',
    ChooseType: 'الرجاء اختيار  النوع',
    ChooseSub: 'الرجاء اختيار القسم الفرعي',
    ChooseMain: 'الرجاء اختيار القسم الرئيسي',
    NoListings: 'لا يوجد لديك منتجات \n تابع لصفحة اضافة منتج',
    NoFavListings: 'لا يوجد لديك منتجات مفضلة \n تصفح المنتجات',
    OR: 'او',
    Yes: 'نعم',
    deleteConfirm: 'هل انت متأكد من حذف المنتج',
    deleteAd: 'حذف المنتج',
    edit: 'تعديل المنتج',
    Used: 'مستعمل',
    New: 'جديد',
    Status: 'الحالة',
    SelectCity: 'اختر المحافظة',
    Bachelor: 'بكالوريوس',
    HighSchool: 'ثانوية عامة    ',
    Experience: 'درجة الخبرة',
    ExperienceYears: 'عدد سنوات الخبرة',
    Degree: 'درجة التعليم    ',
    // Manual:"",
    Area: 'المساحة',
    SelectArea: 'قم بتحديد المساحة',
    Bathrooms: 'الحمامات',
    Bedrooms: 'غرف النوم',
    BedroomsNumber: 'عدد غرف النوم',
    BathroomsNumber: 'عدد الحمامات',
    talabity: 'طلبيتي ',
    DateAdded: 'تاريخ نشر الاعلان    ',
    ChooseCity: 'اختر المحافظة',
    City: 'المحافظة',
    Other: 'اخرى',
    DistanceTraveled: 'المسافة المقطوعة    ',
    Color: 'اللون',

    AdvAddedSuccess: 'تم إضافة اعلانك بنجاح',
    LongPressMain: 'إضغط مطولا للتحديد كصورة رئيسية',

    AddScreenLoginFirst: 'الرجاء تسجيل الدخول \n حتى تتمكن من إضافة إعلان',
    MyListingsLoginFirst: 'الرجاء تسجيل الدخول \n لمشاهدة إعلاناتك',
    MyFavListingsLoginFirst: 'الرجاء تسجيل الدخول \n لمشاهدة إعلاناتك المفضلة',

    gallery: 'ألبوم الصور',
    camera: 'كاميرا',
    ImageSource: 'مصدر الصورة',

    Exit: 'خروج',
    ExitConfirm: 'هل تريد بالتأكيد الخروج من هذا التطبيق',
    YES: 'نعم فعلا',
    OK: 'نعم',
    ViewMyOrders: 'عرض طلبي',
    CANCEL: 'إلغاء',
    Confirm: 'تأكيد',

    ThankYou: 'شكرا',
    Error: 'خطأ',
    Finish: 'إنهاء',

    //Sidemenu
    SignIn: 'تسجيل الدخول',
    SignOut: 'تسجيل الخروج',
    GuestAccount: 'حساب الضيف',
    NoEmailError: 'لا يحتوي حسابك على عنوان بريد إلكتروني صالح',
    Contact: 'اتصل بنا',
    GoToSettings: 'الذهاب الى الإعدادات',
    Login: 'تسجيل الدخول',
    Logout: 'تسجيل الخروج',

    //Checkout
    EnterYourFirstName: 'أدخل اسمك الأول',
    EnterYourLastName: 'أدخل اسم العائلة',
    EnterYourEmail: 'أدخل بريدك الإلكتروني',
    EnterYourPhone: 'أدخل هاتفك',
    EnterYourAddress: 'أدخل عنوانك',
    CreateOrderError: 'أدخل عنوانك...',
    ExpirationDate: 'تاريخ إنتهاء الصلاحية',
    PermissionRequired: 'إذن مطلوب',
    PermissionRequiredText:
      'يجب عليك السماح للوصول للكاميرا والميكروفون لتتمكن من بدء البث',
    symbolPrice: ' د.ع ',
    //settings
    sendOtp: 'تم أرسال رمز التحقق',
    Settings: 'إعدادات',
    BASICSETTINGS: 'الإعدادات الأساسية',
    Language: 'اللغة',
    INFO: 'معلومات',
    About: 'معلومات عنا',
    Ignore: 'تجاهل',
    chooseFromGallery: 'الأختيار من الاستوديو',
    chooseFromCamera: 'التقاط بالكاميرا ',

    //language
    SwitchLanguage: 'تبديل اللغة',
    SwitchLanguageConfirm:
      'تتطلب لغة التبديل إعادة تحميل التطبيق، هل تريد المتابعة؟',

    //contact us
    contactus: 'اتصل بنا',

    //form
    NotSelected: 'لم يتم اختياره',
    EmptyError: 'هذا الحقل فارغ',
    FirstName: 'الاسم الاول',
    Address: 'عنوان',
    NotSelectedError: 'إختر واحد من فضلك',
    Country: 'بلد',
    Email: 'البريد الإلكتروني',
    Phone: 'رقم الهاتف',
    Note: 'ملحوظة',

    //search
    Search: 'بحث',
    NewSearchScreenSearchButton: 'البحث في صوغه',
    SearchPlaceHolder: '  اكتب العبارة',
    NewSearchScreenPlaceHolder: ' مثال:مرسيدس ، بوبجي',
    NoResultError: 'لم تتطابق الكلمة الرئيسية للبحث مع أي منتجات.',
    Details: 'تفاصيل',

    //filter panel
    Categories: 'الاقسام',

    //sign up
    profileDetail: 'تفاصيل الملف الشخصي',
    firstName: 'الاسم الاول',
    accountDetails: 'تفاصيل الحساب',
    username: 'اسم المستخدم',
    email: 'البريد الإلكتروني',
    generatePass: 'استخدام إنشاء كلمة المرور',
    password: 'كلمة السر',
    signup: 'سجل',
    NewSearchScreenLabel: 'البحث في صوغه',
    WhatAreYouSearchingForNew: 'عن ماذا تبحث؟ اكتبه في الأسفل',
    //filter panel
    Loading: 'جار التحميل...',
    welcomeBack: 'مرحبا بعودتك! ',
    seeAll: 'عرض الكل',

    //Layout
    listView: 'عرض القائمة',
    default: 'افتراضي',
    featuredCategories: 'تصانيف مختارة',
    langID: 2,
    browseByCategories: 'الأقسام',
    searchPlaceholder: 'عن ماذا تبحث؟',
    SelectLanguage: 'إختر لغتك',
    ConfirmLanguage: 'تأكيد',
    okLanguage: 'نعم',
    ExtraPostInformation: 'معلومات الإعلان الإضافية',
    CancelLanguage: 'إلغاء',
    NoMessages: 'لا يوجد رسائل',
    WhichItemCategory: 'الرجاء اختيار تصنيف السلعة',
    WhichItemSubCategory: 'الرجاء اختيار التصنيف الفرعي للسلعة',
    PhonePlaceHolder: 'مثال 0798589094',
    ProblemsContact: 'التواصل مع فريق الدعم الفني (واجهتني مشكلة) ',
    downloadImage: 'حفظ الصورة',
    NoImages: 'لم يتم العثور على صور',
    IsDone: ' يتم الأضافة بنجاح ',
    selected: '  مختارة',
    Done: 'تم',
    Youtube: 'يمكنك متابعتنا على اليوتيوب',
    noPermission:
      'لن تستطيع اختيار صور لاعلانك ان لم تسمح لصوغه باستخدام الالبوم',
    AdvertiserName: 'اسم المعلن',
    ContactingYou: 'استفسار حول اعلان: ',
    NoPhone: 'الرجاء ادخال رقم الهاتف',
    Menu: 'القائمة',
    AddPhotosMessage: 'اضافة الصور لاعلانك تزيد نسبة المشاهدة',
    noCameraPermission:
      'لن تستطيع اختيار صور لاعلانك ان لم تسمح لصوغه باستخدام الكاميرا',
    NumOfAds: 'عدد اعلاناتي:',
    MyAuctions: 'مزاداتي',
    MyProfile: 'حسابي',
    AddAuction: 'إضافة مزاد',
    Credits: 'الرصيد',
    Featured: 'المميزون',
    Live: 'المباشرة',
    Upcoming: 'القادمة',
    NoAuctionsFound: 'لا يوجد مزادات لديك',
    NoLiveAuctionsFound: 'لا يوجد مزادات مباشرة',
    NoFeaturedAuctionsFound: 'لا يوجد مزادات مميزة',
    NoUpcomingAuctionsFound: 'لا يوجد مزادات قادمة',
    depositeAmount: 'مبلغ التأمين: *',
    AuctionName: 'اسم المزاد:',
    AuctionInfo: 'معلومات المزاد',
    ItemInfo: 'معلومات العنصر رقم 0',
    ItemName: 'اسم',
    ItemPrice: 'السعر: *',
    OldPrice: 'السعر القديم: *',
    ItemThreshold: 'سعر الحد: *',
    bidJump: 'القفز بالمزايدة: *',
    itemBidJump: 'القفز بالمزايدة:',
    TimerInSecs: 'المؤقت (بالثواني): *',
    WaitAdmin: 'الرجاء الإنتظار لموافقة الاَدمن',
    ImageSource: 'مصدر الصورة',
    album: 'ألبوم الصور',
    AuctionPic: 'صورة المزاد:',
    EnterInfo: 'ادخل المعلومات',
    StartDate: 'تاريخ البداية: *',
    EndDate: 'تاريخ النهاية: *',
    currency: 'العملة: *',
    ChooseCurrency: 'اختر العملة',
    ChooseCountry: 'اختر البلدة',
    AuctionCountry: 'البلدة: *',
    gccShipping: 'تكلفة الشحن \n(داخل الخليج):',
    globalShipping: 'تكلفة الشحن \n(خارج الخليج):',
    numOfItems: 'عدد الأصناف',
    fillItem: 'تعبئة 0 عنصر',
    AddItems: 'إضافة عناصر',
    currentItem: 'العنصر الحالي: ',
    AuctionsWon: 'المزادات التي فزت بها',
    itemID: 'رمز العنصر : #0',
    WonDate: 'تاريخ الفوز : ',
    Paid: 'مدفوع',
    NotPaid: 'غير مدفوع',
    NoRoomsAvailable: 'لا يوجد غرف متاحة حالياً',
    NextItem: 'العنصر التالي',
    CountDown: 'العد التنازلي',
    WaitLiveSetup: 'الرجاء الإنتظار بعض الثواني لتجهيز البث.',
    NoMoreItems: 'لا يوجد عناصر اخرى, يتم الخروج من المزاد.',
    NoOne: 'لا يوجد',
    LeastAmount: ' الحد الأدنى: د.ب ',
    EnterMoreThanLeast: 'الرجاء إدخال رقم اكبر من الحد الأدنى',
    currentItemDetails: 'تفاصيل العنصر الحالي',
    ItemFinished: 'قد انتهت فترة المزايدة على هذا العنصر',
    FillItemsCorrect: 'يرجى تعبئة العناصر بشكل سليم',
    FillEmailCorrect: 'يرجى تعبئة البريد الإلكتروني بشكل سليم',
    FillPasswordCorrect: `
    الرجاء تعبئة كلمة السر بشكل سليم \n
    * يجب أن يكون طوله 6 من (احرف,رموز,ارقام)
    * يجب أن يحتوي على رمز واحد على الأقل
    * يجب أن يحتوي على حرف كبير على الأقل
    * يجب أن يحتوي على رقم واحد على الأقل
    `,
    LanguageAlert: 'سيتم إعادة تشغيل التطبيق لتغيير اللغة',
    Cancel: 'إلغاء',
    AreYouSure: 'هل أنت متأكد؟',
    CamMicPermission:
      'إضغط هنا للسماح للوصول الى الكاميرا والمايكروفون لتتمكن من بدء البث الخاص بك',
    CurrentOffer: 'العرض الحالي: د.ب ',
    SpecialOffer: 'عرض مخصص',
    AuctionStartsFrom: 'تبدأ المزايدة من: د.ب',
    itemNum: 'رقم العنصر: ',
    Offer: 'عرض',
    LastItem: 'هذا اخر عنصر في المزاد.',
    CancelItem: 'تخطي العنصر',
    comingItem: 'العنصر القادم:',
    bidjumpType: 'نوع العرض المخصص:*',
    bidMultiples: 'مضاعفات قيمة القفز',
    bidFree: 'قيم حرة',
    ChooseBidjumpType: 'اختر نوع العرض المخصص',
    OwnerIsOffline: 'لا يوجد بث لأن صاحب المزاد غير متصل',
    ModalTimeout: 'انتهى وقت جسلة الدفع',
    SuccessPayment: 'تمت العملية بنجاح',
    StartAuction: 'بدء المزاد',
    AuctionEnded: 'قد انتهى هذا المزاد.',
    OTPText: 'الرجاء إدخال الرمز المرسل إلى هذا الرقم ',
    ForgotPasswordText: 'الرجاء إدخال رقم الهاتف المتصل مع حسابك.',
    IncorrectOTP: 'الرمز غير صحيح!',
    Chat: 'المحادثات',
    Cart: 'السلة',
    Item: 'صنف',
    OrderHistory: 'سجل الطلبات',
    AvaialbleStores: 'المذاخر المتاحة',
    SendChat: 'المراسلة',
    StoreDetails: 'معلومات المذخر',
    Medicines: 'الأدوية',
    StoreItems: 'منتجات المذخرة',
    JoinStore: 'طلب الدخول والإنضمام',
    ItemDetails: 'معلومات المنتج',
    Stores: 'مذاخر',
    MedicalSupplies: 'مستلزمات طبية',
    AvailableMedicalSupplies: 'المستلزمات الطبية المتاحة',
    ShoppingCartIsEmpty: 'السلة فارغة',
    NoChat: 'لا يوجد محادثات',
    Phonecall: 'مكالمة هاتفية',
    location: 'موقع',
    MyOrders: 'طلبياتي',
    MyInformation: 'معلوماتي',
    Notifications: 'الإشعارات',
    FavoriteStores: 'المذاخر المفضلة',
    FavoriteMedicalSupplies: 'المستلزمات الطبية المفضلة',
    Talabity: 'طلبيتي',
    PleaseSelectCity: 'الرجاء قم باختيار المحافظة',

    MedicineType: 'الشكل الدوائي',
    Delivery: 'التوصيل',
    Points: 'نقاطي',
    OpeningHours: 'ساعات العمل',
    PhoneNumber: 'رقم الهاتف',
    DeliveryTime: 'موعد التسليم',
    StoreArea: 'العنوان',
    AddtoCart: 'أضف إلى السلة',
    GeneralItems: 'المواد العامة',
    Drugs: 'أدوية',
    NewlyAdded: 'وصل حديثاً',
    ExpireDate: 'تاريخ الإنتهاء',
    OTP: 'رمز التأكد ',
    Provider: 'الشركة المنتجة',
    Cameback: 'وصل بعد انقطاع',
    RequestPrice: 'أعرض السعر',
    PointsText: 'احصل على * نقطة لكل قطعة.',
    Offers: 'العروض',
    DisplayMore: 'عرض المزيد',
    MaxItems: 'يمكنك فقط شراء * قطعة.',
    OfferEndsIn: 'العرض ينتهي بعد * أيام.',
    BonusText: 'احصل على * قطعة كل ^ قطعة.',
    Bonus: 'نقطه .',
    Piece: 'قطعه .',
    TalabityApp: 'تطبيق طلبيتي',
    TalabityAppMessage:
      ':يمكنك الان تثبيت تطبيق طلبيتي على\n\nhttps://play.google.com/store/apps/details?id=com.talabity&hl=en',
    CantBuyFromDiffStores: 'لا يمكنك الشراء من أكثر من مكان في نفس السلة.',
    ItemAlreadyExists:
      'السلعة موجودة حاليا في السلة, الرجاء تعديل الكمية من السلة مباشرة.',
    ClearCart: 'مسح السلة',
    OrderFrom: 'طلب من *',
    Checkout: 'أرسل الطلب',
    NoPrice: 'دون سعر',
    ItemQuantity: ' x^ * ',
    TotalPrice: 'السعر الكلي: *$',
    Go: 'اذهب',
    TypeAMessage: 'اكتب رسالة...',
    CopyText: 'انسخ النص',
    EnableLocation: 'الرجاء تفعيل صلاحية الموقع',
    Hours: 'ساعة',
    Minutes: 'دقيقة',
    InactiveAccount: 'لم يتم الموافقة على هذا الحساب.',
    ChangePassword: 'تغيير كلمة السر',
    CurrentPassword: 'كلمة السر الحالية',
    IncorrectPassword: 'كلمة السر الحالية غير صحيحة',
    DataEditedSuccessfully: 'تم تعديل البيانات بنجاح',
    AddPharmacy: 'أضف صيدلية',
    EditPharmacy: 'تعديل معلومات صيدلية',
    MyPharmacies: 'صيدلياتي',
    CartCheckoutSuccessful: 'تم الطلب بنجاح',
    EnterArabicName: 'أدخل أسم الصيدلية بالعربي',
    EnterEnglishName: 'أدخل أسم الصيدلية بالأنجليزي',
    LocationAr: 'العنوان  بالعربي',
    LocationEn: 'العنوان بالأنجليزي',
    FillWithValidData: 'عبئ الخانات ببيانات فعالة',
    Attention: 'أنتباه',
    AreYouSureDeletePharmacy: 'هل أنت متأكد من حذف الصيدلية؟',
    AddUser: 'إضافة مستخدم',
    AddedSuccessfully: 'تم الإضافة بنجاح',
    UserExist: 'المستخدم موجود',
    MaxPriceRequest: 'لقد وصلت للحد اليومي الأعلى المسموح لطلب السعر',
    CountShowPrice: ' المتبقي للحد اليومي هو ',
    Members: 'الأعضاء',
    NoMembers: 'لا يوجد أعضاء',
    MemberRemoved: 'تم إزالة العضو',
    AreYouSureDeleteMember: 'هل أنت متأكد من حذف العضو؟',
    AbouUsParagraph:
      'عش التجربة وجهز طلبيتك من الادوية او المستلزمات الطبية بكبسة زر وانت جالس في مقعدك. && مع Talabeety كل ماتحتاجه صيدليتك يصل اليك بسرعة ودقة, تطبيق واحد يسهل عليك عناء البحث وتجميع المواد ومتابعة سير الطلب, هذا مايوفره لك Talabeety كل ما عليك. تحميل تطبيق Talabeety من الابل ستور أو الأندرويد, لتتعرفوا على هذا التطبيق اكثر و لتستمتعوا بالعروض والاسعار الخاصة إضافة إلى تجميع النقاط التي يمكن استبدالها مستقبلا بعروض خاصه من المذخر او محلات المستلزمات الطبيه, كل هذا لا تجدوها إلا في (Talabeety)',
    NoEnoughInfo: 'لا توجد معلومات كافية عن هذا المنتج',
    EnterValidEmail: 'أدخل بريد الكتروني صحيح',
    EnterValidPhoneNumber: 'أدخل رقم هاتف صحيح',
    RegisterRequestPending:
      'طلب التسجيل بانتظار موافقة الأدمن خلال 24 ساعة . لطلب المساعدة اضغط على اتصل بنا ',
    Success: 'نجاح',
    PrivacyPolicy: 'سياسة الخصوصية',
    GoToLocation: 'الذهاب للموقع',
    SoldByDozen: 'يباع بالدرزن',
    SoldByItem: 'يباع بالقطعة',
    GetPointsByQuantity: 'أحصل على $ نقاط كل & قطع',
    NoAvailableQuantity: 'غير متوفر',
    ArrivedToday: 'وصل اليوم',
    ArrivedAfterCutout: 'وصل بعد أنقطاع',
    ArrivedNew: 'وصل حديثاً',
    New: 'جديد',
    StoreSales: 'عروض المذخر',
    FavouriteItems: 'الأدوية المفضلة',
    Reorder: 'إعادة الطلب',
    SureToReorder: 'هل أنت متأكد من إعادة الطلب مرةأخرى؟',
    ReorderedSuccessfully: 'تم إعادة الطلب بنجاح',
    CancelOrder: 'إلغاء الطلب',
    No: 'لا',
    SureToCancelOrder: 'هل أنت متأكد من إلغاء الطلب؟',
    OrderTotal: 'مجموع الطلب: ',
    Cancelled: 'ملغي',
    New: 'جديد',
    Pending: 'قيد التجهيز',
    Paid: 'مدفوع',
    Complete: 'منتهي',
    NotePlaceholder: '...أكتب ملاحظتك هنا',
    BuyerName: 'أسم المشتري: ',
    senderName: 'أسم المرسل: ',
    Preparing: 'بالتجهيز',
    Shipped: 'بالطريق',
    Finished: 'استلمت',
    completed: 'جاهزة',
    Favourites: 'المفضلة',
    ScienteficName: 'الأسم العلمي: *',
    DrugForm: 'شكل الدواء: ',
    OrderInfo: 'حالة الطلب',
    SingleItemPrice: 'سعر المنتج: *',
    SingleItemTotalPrice: 'السعر الإجمالي للمنتج: *',
    Quantity: 'الكمية: *',
    UsePoints: 'أستخدام نقاطي',
    NoPointsInThisDrugStore: 'لا يوجد لديك نقاط في هذا المذخر',
    MyPoints: 'نقاطي: *',
    TotalPriceAfterSale: 'السعر الكلي بعد الخصم: *',
    Free: 'مجاني',
    ReplacePointsMessage: 'لإستبدال النقاط أذهب لصفحة المتجر وتسوق',
    TotalSaleAmount: 'مجموع مبلغ الخصم: *',
    OrderDate: 'تاريخ و وقت الطلب: ',
    AmountOfUsedPoints: 'عدد النقاط المستخدمة: ',
    NoProductsHere: ' لا يوجد منتجات هنا يمكنك البحث ',
    SelectImage: 'أختر صورة',
    AddOpenPharmacyAccess: 'أضف صورة إجازة فتح الصيدلية',
    TermsAndConditions: 'الشروط و الأحكام',
    getPoints: 'قم بالتسوق للحصول على النقاط',
    usedPoints: 'النقاط المستخدمة',
    minPoint:
      ' الحد الأدنى لإستبدال النقاط هو  && ! في حال إكمال الطلب لن يتم تطبيق النقاط ...هل انت متاكد من اكمال طلبك ؟',
  },
  en: {
    minPoint:
      'The minimum amount to redeem is && points! Points will not be applied if the Order is completed... Do you want to complete the Order',
    symbolPrice: ' IQD ',
    usedPoints: 'used Points',
    getPoints: 'Shop now to get points',
    TermsAndConditions: 'Terms and conditions',
    AddOpenPharmacyAccess: 'Add pharmacy license image',
    SelectImage: 'Select image',
    NoProductsHere: 'There are no products here you can search',
    AmountOfUsedPoints: 'Amount of points used: ',
    TotalSaleAmount: 'Total sale amount: *',
    ReplacePointsMessage: 'To replace points go to the store page and shop',
    Free: 'Free',
    TotalPriceAfterSale: 'Total price after discount: *',
    MyPoints: 'MyPoints: *',
    NoPointsInThisDrugStore: 'You dont have points in this drug store',
    Quantity: 'Quantity: *',
    SingleItemTotalPrice: 'Item total price: *',
    SingleItemPrice: 'Item price: *',
    OrderInfo: 'Order info',
    ScienteficName: 'Scientefic name: *',
    Favourites: 'Favourites',
    Preparing: 'Preparing',
    Shipped: 'Shipped',
    Finished: 'Finished',
    BuyerName: 'Buyer Name: ',
    senderName: 'Sender Name: ',
    NotePlaceholder: 'Write your note here...',
    Cancelled: 'Cancelled',
    New: 'New',
    Pending: 'Pending',
    Paid: 'Paid',
    Complete: 'Complete',
    SureToCancelOrder: 'Are you sure to cancel order?',
    No: 'No',
    CancelOrder: 'Cancel order',
    ReorderedSuccessfully: 'Reordered successfully',
    Reorder: 'Reorder',
    Youtube: 'You can follow us on YouTube',
    SureToReorder: 'Are you sure to reorder?',
    ArrivedToday: 'Arrived today',
    ArrivedAfterCutout: 'Arrived after a break',
    ArrivedNew: 'Newly Arrived',
    New: 'New',
    StoreSales: 'Sales',
    facebook: 'FaceBook ',
    instagram: 'Instagram ',
    whatsappContact: 'Cotact us via Whatsapp',
    FavouriteItems: 'Favourites',
    NoAvailableQuantity: 'No available quantity',
    GetPointsByQuantity: 'Get $ points every & items',
    SoldByDozen: 'Sold by dozen',
    SoldByItem: 'Sold by item',
    GoToLocation: 'Go to location',
    PrivacyPolicy: 'Privacy policy',
    Success: 'Success',
    RegisterRequestPending:
      'Register request waiting for accept from admin within 24 hours,To request assistance, click on Contact Us',
    EnterValidEmail: 'Enter valid email',
    EnterValidPhoneNumber: 'Enter valid phone number',
    NoEnoughInfo: 'No enough info about this product',
    AbouUsParagraph:
      'Live the experience and prepare your order of medicines or medical supplies with the push of a button while you are sitting in your seat. && with Talabeety. Everything your pharmacy needs reaches you and the accuracy of one application makes it easy for you to bother searching, collecting materials and following up on the progress of the order, Download the Talabeety application from the Apple Store or Android to know more about this application and To enjoy special offers, in addition to accumulating points that you can enjoy in the future with special offers from Al-Muthkhir, all of this can only be found here (Talabeety)',
    AreYouSureDeleteMember: 'Are you sure delete pharmacy?',
    MemberRemoved: 'Member removed',
    NoMembers: 'No members',
    Members: 'Members',
    MaxPriceRequest: 'Daily maximum price requests reached',
    UserExist: 'User exists',
    AddedSuccessfully: 'Added successfully',
    AddUser: 'Add User',
    IsUserName: 'This name exists',
    IsPhone: 'This Number exists',
    EditUser: 'Edit User',
    AreYouSureDeletePharmacy: 'Are you sure you want to delete pharmacy?',
    Attention: 'Attention',
    FillWithValidData: 'Fill fields with valid data',
    LocationAr: 'Arabic Address',
    LocationEn: 'English Address',
    EnterArabicName: 'Enter arabic name pharmacy',
    EnterEnglishName: 'Enter  english name pharmacy',
    CartCheckoutSuccessful: 'Cart checkout successfully',
    MyPharmacies: 'My Pharmacies',
    AddPharmacy: 'Add Pharmacy',
    DataEditedSuccessfully: 'Data was edited successfully',
    IncorrectPassword: 'The current password is incorrect',
    CurrentPassword: 'Current Password',
    ChangePassword: 'Change Password',
    InactiveAccount: 'This account has not been approved.',
    Hours: 'Hours',
    Minutes: 'Minutes',
    CopyText: 'Copy Text',
    TypeAMessage: 'Type a message...',
    Go: 'Go',
    ItemQuantity: ' x^ * ',
    NoPrice: 'No Price',
    OrderFrom: 'Order from *',
    ClearCart: 'Clear Cart',
    talabity: 'Talabity App',
    ItemAlreadyExists:
      'The item is currently in the basket, please modify the quantity directly from the basket',
    CantBuyFromDiffStores:
      'You cannot buy from more than one place in the same basket.',
    TalabityAppMessage:
      'You can install Talabity now at:\nhttps://play.google.com/store/apps/details?id=com.talabity&hl=en',
    TalabityApp: 'Talabity App',
    BonusText: 'Get * pieces for each ^ pieces.',
    OfferEndsIn: 'Offer ends in * days.',
    MaxItems: 'You can only buy * pieces from this seller.',
    DisplayMore: 'More',
    Offers: 'Offers',
    PointsText: 'Get * points per piece.',
    RequestPrice: 'Show Price',
    Cameback: 'Arrived after a break',
    Provider: 'Provider',
    ExpireDate: 'Expire Date',
    NewlyAdded: 'Newly Added',
    GeneralItems: 'General Items',
    Drugs: 'Drugs',
    StoreArea: 'Address',
    DeliveryTime: 'Delivery Time',
    PhoneNumber: 'Phone Number',
    OpeningHours: 'Opening Hours',
    Points: 'Points',
    Delivery: 'Delivery',
    MedicineType: 'Medicine Type',
    resendOtp: 'Send an Otp',
    PleaseSelectCity: 'Please select the wanted city',
    Talabity: 'Talabity',
    FavoriteStores: 'Favorite Stores',
    FavoriteMedicalSupplies: 'Favorite Medical Supplies',
    Notifications: 'Notifications',
    MyInformation: 'Information',
    MyOrders: 'Orders',
    Phonecall: 'Phone Call',
    location: 'Location',
    NoChat: 'No open conversations',
    Minimumpoints: 'Minimum points to redeem',
    AvailableMedicalSupplies: 'Available Medical Supplies',
    Stores: 'Stores',
    MedicalSupplies: 'Medical Supplies',
    ItemDetails: 'Item Details',
    JoinStore: 'Join Store',
    StoreItems: 'Store Items',
    Medicines: 'Medicines',
    StoreDetails: 'Store Details',
    SendChat: 'Send Chat',
    AvaialbleStores: 'Avaialble Stores',
    OrderHistory: 'Order History',
    Chat: 'Chat',
    IncorrectOTP: 'OTP is incorrect!',
    ForgotPasswordText:
      'Please enter the phone number linked with your account.',
    OTPText: 'Please enter the code sent at this number ',
    AuctionEnded: 'This auction has ended.',
    StartAuction: 'Start Auction',
    SuccessPayment: 'Payment done successfully',
    ModalTimeout: 'Payment session has been timed out.',
    OwnerIsOffline: 'No broadcast because the auctioneer is offline',
    ChooseBidjumpType: 'Choose bidjump type',
    bidFree: 'bid jump free',
    bidMultiples: 'bid jump multiples',
    bidjumpType: 'Special Offer Type:*',
    comingItem: 'coming item:',
    CancelItem: 'Cancel Item',
    LastItem: 'This is the last item in the auction',
    Offer: 'Offer',
    itemNum: 'Item Number: ',
    AuctionStartsFrom: 'Auction Starts from:  BHD',
    SpecialOffer: 'Custom Offer',
    OrderOmnerName: 'Applicant Name : ',
    CurrentOffer: 'Current Offer: BHD ',
    CamMicPermission:
      'Click here to allow access to the camera and microphone to be able to start your broadcast',
    AreYouSure: 'Are you sure?',
    Cancel: 'Cancel',
    StoreroomsAdded: 'Storerooms Added',
    LanguageAlert: 'The app will restart to apply the language change',
    FillPasswordCorrect: `
    Please fill in the password correctly \n
    * It must be 6 in length (letters, symbols, numbers)
    * It must contain at least one symbol
    * It must contain at least one capital letter
    * It must contain at least one number
    `,
    FillEmailCorrect: 'Please fill in the email correctly',
    EnableLocation: 'Please enable location services to choose ur location',
    FillItemsCorrect: 'Please fill the items correctly.',
    ItemFinished: 'The bidding period for this situation has expired',

    completed: 'Complete',
    itemID: 'Item ID : #0',
    Yes: 'Yes',
    currentItemDetails: 'Current item details',
    EnterMoreThanLeast: 'Please enter a number greater than the minimum',
    LeastAmount: ' Least Amount: BHD ',
    NoOne: 'none',
    NoMoreItems: 'No other items, you are exiting the auction.',
    WaitLiveSetup: 'Please wait a few seconds to prepare the broadcast.',
    CountDown: 'Start Countdown',
    NextItem: 'Next Item',
    NoRoomsAvailable: 'Unfortunately, There are no rooms available.',
    NotPaid: 'Not Paid',
    Paid: 'Paid',
    WonDate: 'Won Date : ',
    AuctionsWon: 'Auctions you won before',
    currentItem: 'Current Item: ',
    AddItems: 'Add Items',
    fillItem: 'Fill 0 items',
    numOfItems: 'Num of Items',
    globalShipping: 'Shipping (global):',
    gccShipping: 'Shipping (gcc):',
    AuctionCountry: 'Country: *',
    ChooseCountry: 'Choose Country',
    ChooseCurrency: 'Choose Currency',
    currency: 'Currency: *',
    EndDate: 'End Date: *',
    StartDate: 'Start Date: *',
    EnterInfo: 'Enter Info',
    AuctionPic: 'Auction Picture:',
    album: 'album',
    ImageSource: 'Image Source',
    WaitAdmin: 'Please wait for admin approval',
    TimerInSecs: 'Timer (Secs): *',
    bidJump: 'Bid Jump: *',
    itemBidJump: 'Bid Jump:',
    ItemThreshold: 'Threshold: *',
    ItemPrice: 'Price: *',
    OldPrice: 'Old price: *',
    ItemName: 'Name',
    ItemInfo: 'Info for item #0',
    AuctionInfo: 'Auction Info',
    AuctionName: 'Auction Name:',
    depositeAmount: 'Deposite Amount: *',
    NoLiveAuctionsFound: 'No Live Auctions Were Found',
    NoFeaturedAuctionsFound: 'No Featured Auctions Were Found',
    NoUpcomingAuctionsFound: 'No Upcoming Auctions Were Found',
    NoAuctionsFound: 'No Auctions Were Found',
    Upcoming: 'Upcoming',
    Live: 'Live',
    Featured: 'Featured',
    Credits: 'Credits',
    AddAuction: 'Add Auction',
    MyProfile: 'Profile',
    MyAuctions: 'My Auctions',
    Menu: 'Menu',
    ContactingYou: 'Contacting You about Ad: ',
    owner: 'Owner Pharmacy',
    AdvertiserName: 'Advertiser Name',
    IsDone: ' Added to successfully',
    noPermission:
      'You wont be able to select images if you dont give sooqa permissions to your gallery',
    Done: 'Done',
    selected: ' selected',
    NoImages: 'No Images Found',
    totalpoint: 'Not enough points to redeem ',
    downloadImage: 'Save Image',
    ProblemsContact: 'Contact us if you encounter any problems.',
    SelectLanguage: 'Choose your language',
    ConfirmLanguage: 'Confirm',
    okLanguage: 'Yes',
    WhichCategory: 'Please Choose The Post Category',
    whatsapp: 'WhatsApp is not installed',
    CancelLanguage: 'Cancel',
    NoMessages: 'No Messages',
    WhichSubCategory: 'Please Choose The Post Subcategory',
    ByContinuing: 'By continuing you agree to',
    Terms: 'the term of service',
    LoginOperation: 'Login Operation',
    Skip: 'Skip',
    PostGeneralInformation: 'General Information',
    YouCan: 'You can',
    ConfirmPassword: 'Confirm Password',
    AndPrivacy: 'and privacy policy',
    RegisterNow: 'Register now',
    LoginNow: 'Login now',
    LatestAds: 'Latest Advertisments',
    HaveAccount: 'Have an account?',
    applicationCanOnly:
      'The application can only be used if your pharmacy is registered',
    NoAccount: 'Dont have an account?',
    Name: 'Name',
    ForgotPassword: 'Forgot Password?',
    Exit: 'Exit',
    ExitConfirm: 'Are you sure you want to exit this app',
    YES: 'YES',
    OK: 'OK',
    ViewMyOrders: 'View My Oders',
    CANCEL: 'CANCEL',
    Confirm: 'Confirm',

    //Scene's Titles
    Home: 'Home',
    brands: 'Brands',
    Intro: 'Intro',
    Product: 'Product',
    Cart: 'Cart',
    WishList: 'WishList',

    //Home
    products: 'products',

    //TopBar
    ShowFilter: 'Sub Categories',
    HideFilter: 'Hide',
    Sort: 'Sort',
    textFilter: 'Recent',
    Enterotp: 'Enter the verification code',
    //Category
    ThereIsNoMore: 'There is no more product to show',

    //Product
    AddtoCart: 'Add to Cart',
    AddtoWishlist: 'Add to Wishlist',
    NewSearchScreenLabel: 'Search In Souq Haretna',
    ProductVariations: 'Variations',
    NoVariation: "This product don't have any variation",
    AdditionalInformation: 'Description',
    NoProductDescription: 'No Product Description',
    ProductReviews: 'Reviews',
    NoReview: "This product don't have any reviews ...yet",
    BUYNOW: 'BUY NOW',
    ProductLimitWaring: "You can't add more than 10 product",
    OrderNum: ' Order Number :',
    EmptyProductAttribute: "This product don't have any attributes",
    ProductFeatures: 'Features',
    ErrorMessageRequest: "Can't get data from server",
    NoConnection: 'No internet connection',
    ProductRelated: 'You May Also Like',

    //Cart
    NoCartItem: 'There is no product in cart',
    Total: 'Total',
    EmptyCheckout: "Sorry, you can't check out an empty cart",
    RemoveCartItemConfirm: 'Remove this product from cart?',
    MyCart: 'Cart',
    Order: 'Order',
    ShoppingCart: 'Shopping Cart',
    ShoppingCartIsEmpty: 'Your Cart is Empty',
    Delivery: 'Delivery',
    AddProductToCart: 'Add a product to the shopping cart',
    TotalPrice: 'Total Price: *$',
    YourDeliveryInfo: 'Your delivery info:',
    ShopNow: 'Shop Now',
    YourChoice: 'Your wishlist:',
    YourSale: 'Your Sale:',
    searchProduct: 'Search Product',
    SubtotalPrice: 'Subtotal Price:',
    BuyNow: 'Buy Now',
    Items: 'items',
    Item: 'item',
    ThankYou: 'Thank you',
    FinishOrderCOD: 'You can use to number of order to track shipping status',
    FinishOrder:
      'Thank you so much for your purchased, to check your delivery status please go to My Orders',
    NextStep: 'Next Step',
    ConfirmOrder: 'Confirm Order',
    RequireEnterAllFileds: 'Please enter all fields',
    Error: 'Error',
    InvalidEmail: 'Invalid email address',
    Finish: 'Finish',

    //Wishlist
    NoWishListItem: 'There is no item in wishlist',
    MoveAllToCart: 'Add all to cart',
    EmptyWishList: 'Empty wishlist',
    EmptyAddToCart: 'Sorry, the wishlist is empty',
    RemoveWishListItemConfirm: 'Remove this product from wishlist?',
    CleanAll: 'Clean All',
    Ignore: 'Ignore',
    //Sidemenu
    SignIn: 'Log In',
    SignOut: 'Log Out',
    EditPharmacy: 'Edit Pharmacy ',
    GuestAccount: 'Guest Account',
    CantReactEmailError:
      "We can't reach your email address, please try other login method",
    NoEmailError: "Your account don't have valid email address",
    EmailIsNotVerifiedError:
      "Your email address is not verified, we can' trust you",
    Shop: 'Shop',
    News: 'News',
    Contact: 'Contact Us',
    Login: 'Login',
    Logout: 'Logout',
    SwitchLanguage: 'Switch Language',
    SwitchLanguageConfirm: 'Switch language require an app reload, continue?',

    //Checkout
    Checkout: 'Checkout',
    ProceedPayment: 'Proceed Payment',
    Purchase: 'Purchase',
    CashOnDelivery: 'Cash on Delivery',
    Paypal: 'Paypal',
    Stripe: 'Stripe',
    CreditCard: 'Credit Card',
    PaymentMethod: 'Payment Method - Not select',
    PaymentMethodError: 'Please select your payment method',
    PayWithCoD: 'Your purchase will be pay when goods were delivered',
    PayWithPayPal: 'Your purchase will be pay with PayPal',
    PayWithStripe: 'Your purchase will be pay with Stripe',
    UsePoints: 'Use my points',
    CouponPlaceholder: 'COUPON CODE',
    APPLY: 'APPLY',
    Back: 'Back',
    CardNamePlaceholder: 'Name written on card',
    BackToHome: 'Back to Home',
    OrderCompleted: 'Your order was completed',
    OrderCanceled: 'Your order was canceled',
    OrderFailed: 'Something went wrong...',
    DrugForm: 'Drug Form:',
    OrderCompletedDesc: 'Your order id is ',
    OrderCanceledDesc:
      'You have canceled the order. The transaction has not been completed',
    OrderFailedDesc:
      'We have encountered an error while processing your order. The transaction has not been completed. Please try again',
    OrderTip:
      'Tip: You could track your order status in "My Orders" section from side menu',
    Payment: 'Payment',
    Complete: 'Complete',
    EnterYourFirstName: 'Enter your First Name',
    EnterYourLastName: 'Enter your Last Name',
    EnterYourEmail: 'Enter your email',
    EnterYourPhone: 'Enter your phone',
    EnterYourAddress: 'Enter your address',
    CreateOrderError: 'Cannot create new order. Please try again later',
    AccountNumner: 'Account number',
    CardHolderName: 'Cardholder Name',
    ExpirationDate: 'Expiration Date',
    SecurityCode: 'CVV',

    //myorder
    MyOrder: 'My Order',
    NoOrder: "You don't have any orders",
    OrderDate: 'Order Date Or Time: ',
    OrderStatus: 'Status: ',
    OrderPayment: 'Payment method: ',
    OrderTotal: 'Total: ',
    OrderDetails: 'Show detail',
    chooseFromCamera: 'Take a Picture ',

    PhonePlaceHolder: 'Ex. 0796592041',
    PostDetails: 'Post Details',
    FeatureArticles: 'Feature articles',
    MostViews: 'Most views',
    EditorChoice: 'Editor choice',

    //settings
    Settings: 'Settings',
    BASICSETTINGS: 'BASIC SETTINGS',
    Language: 'Language',
    INFO: 'INFO',
    About: 'About us',
    changeRTL: 'Switch RTL',

    //language
    AvailableLanguages: 'Available Languages',
    SwitchRtlConfirm: 'Switch RTL require an app reload, continue?',

    //about us
    AppName: 'MSTORE',
    AppDescription: 'React Native template for mCommerce',
    AppContact: ' Contact us at: mstore.io',
    AppEmail: ' Email: support@mstore.io',
    AppCopyRights: '© MSTORE 2016',

    //contact us
    contactus: 'Contact Us',

    //form
    NotSelected: 'Not selected',
    EmptyError: 'This field is empty',
    DeliveryInfo: 'Delivery Info',
    FirstName: 'First Name',
    LastName: 'Last Name',
    Address: 'Address',
    State: 'State/City',
    NotSelectedError: 'Please choose one',
    Postcode: 'Postcode',
    Country: 'Country',
    Email: 'Email',
    Phone: 'Phone Number',
    Note: 'Note',
    GoToSettings: 'Go to settings',
    //search
    Search: 'Search',
    SearchPlaceHolder: 'Search product by name',
    NoResultError: 'Your search keyword did not match any products.',
    Details: 'Details',

    //filter panel
    Categories: 'Categories',

    //sign up
    profileDetail: 'Profile Details',
    firstName: 'First name',
    lastName: 'Last name',
    accountDetails: 'Account Details',
    username: 'Username',
    email: 'Email',
    generatePass: 'Use generate password',
    password: 'Password',
    signup: 'Sign Up',

    //filter panel
    Loading: 'LOADING...',
    welcomeBack: 'Welcome back! ',
    seeAll: 'Show All',
    Piece: 'Piece .',
    //Layout
    cardView: 'Card ',
    WhichItemCategory: 'Please Choose The Item Category',
    WhichItemSubCategory: 'Please Choose The Item Subcategory',
    simpleView: 'List View',
    twoColumnView: 'Two Column ',
    threeColumnView: 'Three Column ',
    listView: 'List View',
    default: 'Default',
    advanceView: 'Advance ',
    horizontal: 'Horizontal ',

    //KEnsoftware
    featuredCategories: 'Featured Categories',
    langID: 1,
    browseByCategories: 'Categories',
    searchPlaceholder: 'What are you looking for?',
    camera: 'camera',
    AdvAddedSuccess: 'Listing Added successfully',
    SomethingWentWrong: 'Something Went Wrong',
    NewMessage: 'You have a new message',
    OpenMessage: 'Do you want to open messages',
    close: 'Close',
    ShareApp: 'Share',
    Bonu: 'Bonus .',
    DownloadSouqHaretna: ':Download Souq Haretna',
    NewSearchScreenSearchButton: 'Search In Souq Haretna',
    AppPolicy: 'Application policy',
    Messages: 'Messages',
    LoginFirst: 'You must login to see your messages.',
    NewSearchScreenPlaceHolder: 'Ex. Mercedes, PUBG',
    Report: 'Report',
    IncorrectNumber: 'Invalid user number',
    ShareMsg: 'See this ad on Souq Haretna',
    SouqHaretnaDesc:
      'صوغه: الموقع الأحدث في العراق للبيع و البحث عن العقارات, السيارات',
    EducationLevel: 'Education Level',
    EditAdv: 'Edit Listing',
    Location: 'Location',
    SelectLocation: 'Select Location',
    Automatic: 'Automatic',
    Manual: 'Manual',
    GearType: 'Transimission',
    SelectPrice: 'Select Price',
    Model: 'Model',
    SelectColor: 'Select Color',
    Price: 'Price',
    SelectKind: 'Select Category',
    Kind: 'Category',
    SubCategory: 'Sub Category',
    ChooseSubCat: 'Select Sub Category',
    SelectType: 'Select Type',
    ChooseMainCat: 'Select a main category',
    Type: 'Type',
    AllCats: 'All Categories',
    IraqDinar: 'IQD',
    Dollar: 'USD',
    NoItems: 'No Items',
    SaveChanges: 'Save Changes',

    ExtraPostInformation: 'Extra Information',
    MyFavourites: 'My Favourites',
    MyAds: 'My Listings',
    CountShowPrice: 'The remaining daily limit is ',
    AddAdvertismentHeader: 'Submit Listing',
    sendOtp: 'The verification code was sent',
    AddAdvertisment: 'Submit Listing On Souq Haretna For Free',
    EnterWordToSearch: 'Enter Search Keyword',
    ChooseCat: 'Choose Category',
    OR: 'Or',
    CategoriesSearch: 'Search',
    AddAdvs: 'Submit Listing',
    ShowMore: '  Show more',
    SeeCatgs: 'Browse Categories',
    FillCorrect: 'Please fill the data correctly.',
    TryAgain: 'Try again later',
    EmailUsed: 'Email Address is already used',
    EmailOrPassIncorrect: 'Email or Password Incorrect',
    savedChanges: 'Changes Saved Successfully',
    search: 'Search',
    Share: 'Share ',
    WhatAreYouSearchingForNew: 'What Are You Searching For? Write It Below',
    Town: 'City',
    SelectTown: 'Select City',

    MustLogin: 'You Must Login First',
    EditProfile: 'Edit Profile',
    WrongCode: 'Wrong Code',
    BackToLogin: 'Back to login',
    PasswordChanged: 'Password Change',
    PasswordDoesntMatch: "Password Didn't Match",
    PasswordIsShort: 'Password is too short',
    NewPassword: 'New Password',

    VerifyText: 'Waiting Verification Code',
    YourCode: 'Your Code', //otp code placeholder
    Verify: 'Verify',
    OTP: 'OTP',
    Resend: 'Resend',
    send: 'Send',
    Submit: 'Submit',
    EnterEmail: "Enter your email and we'll send you confirmation code",

    PrivacyAndPolicy:
      'By Continuing you agree to terms of service and privacy policy.',
    Title: 'Title',
    SelectTitle: 'Select Title',
    noCameraPermission:
      'You wont be able to select images if you dont give sooqa permissions to your camera',
    Description: 'Description',
    chooseFromGallery: 'Choose From Gallery',
    SelectDescription: 'Enter Description',
    Photos: 'Add Photos To The Post',
    NoTitle: 'Please Fill Title',
    ChooseKind: 'Please Select Category',
    PermissionRequired: 'Permission required',
    PermissionRequiredText:
      'You must allow access to the camera and microphone in order to start broadcasting',
    ChooseType: 'Please Select Type',
    ChooseSub: 'Please Select Sub Category',
    ChooseMain: 'Please Select Main Category',
    NoListings: 'No Listings.. \n Continue To Add Listing',
    NoFavListings: 'No Favourites ..\n Browse Listings',

    deleteConfirm: 'Are you sure you want to delete this listing',
    deleteAd: 'Delete Listing',
    edit: 'Edit Listing',
    Used: 'Used',
    New: 'New',
    Status: 'Status',
    SelectCity: 'Select City',
    Bachelor: 'Bachelor',
    HighSchool: 'Highschool    ',
    Experience: 'Experience Level',
    ExperienceYears: 'Experience Years',
    Degree: 'Degree    ',
    // Manual:"",
    Area: 'Area',
    SelectArea: 'Select Area',
    Bathrooms: 'Bathrooms',
    Bedrooms: 'Bedrooms',
    BedroomsNumber: 'Bedrooms Number',
    BathroomsNumber: 'Bathroom Number',
    DateAdded: 'Date Added    ',
    ChooseCity: 'Select State',
    City: 'City',
    Other: 'Other',
    DistanceTraveled: 'Distance Traveled    ',
    Color: 'Color',
    LongPressMain: 'Long press to set as main picture',

    AddScreenLoginFirst: 'You must login to add a listing',
    MyListingsLoginFirst: 'You must login to view your listings',
    MyFavListingsLoginFirst: 'You must login to see favourite listings',

    gallery: 'Gallery',
    ImageSource: 'Image Source',

    //filter panel

    NoPhone: 'Please enter your phone number',

    //Layout

    AddPhotosMessage:
      'Adding photos to your advertisment increases your advertisment views',
    NumOfAds: 'My Advertisments Count:',
  },
});
